### PR TITLE
Limit all memory allocations in the MemoryAllocator layer

### LINKED ISSUE #2696: File (detected as bmp) fails to open, consumes a lot of memory
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.3

### Other ImageSharp packages and versions

N/A

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

.net 8

### Description

The attached (zipped) file, 126 bytes long, gives an out-of-memory error when I try to open it with the following code:

```
using FileStream stream = File.OpenRead("00271-imageworsener-leftshift");
SixLabors.ImageSharp.Image.Load(stream);
```

I believe there is a problem with the image dimensions - BmpDecoderCore.ReadImageHeaders sets this.infoHeader.Width and this.infoHeader.Height to very high values which tries to create a huge image in BmpDecoderCore.Decode().

### Steps to Reproduce

See description.

### Images

[00271-imageworsener-leftshift.zip](https://github.com/SixLabors/ImageSharp/files/14583779/00271-imageworsener-leftshift.zip)

### PR DESCRIPTION
**Pull request by antonfirsov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Fixes #2696.

This is an alternative take for #2704. Differences:
- The discontiguous limit is configurable in Megabytes on `MemoryAllocatorOptions` (together with the pool size).
    - On 64bit it defaults to 4GB, equivalent of `32k x 32k` of `Rgba32` which is more conservative than the limit in #2704. For me this feels somewhat safer while I don't see many downsides. Note that this is the absolute hardcoded limit in WIC, while newer [skia builds have a hardcoded 2GB limit](https://github.com/google/skia/commit/e262e688247792e9a7e31355a3e00315e606c0b3) (this hasn't been merged to in SkiaSharp 2.* yet)
    - On 32bit it defaults to 1GB which is a significant portion of the overall virtual memory limit of 4GB. Maybe we can make it even lower.
- Single contiguous buffers have a limit of 1GB (or the discontiguous limit, if it's lower). This limit is not configurable separately in order to make things simpler for users. I don't see any risks from that nor the need to make it as low as in #2704. The RLE path in BMP and TIFF decoders actually allocates temporary contiguous buffers of `width * height` sizes so a 64MB limit would be easy to exceed with sane images.
- It also significantly reduces `MaxAllocationAttempts` so we don't block too long if an OOM is still being hit.

The PR is missing tests and PNG tweak from #2704. Will finalize it after agreeing on the direction.

### CODE REVIEW

File: src/ImageSharp/Memory/Allocators/MemoryAllocator.cs [hunk 1]
```diff
@@ -20,6 +24,12 @@ public abstract class MemoryAllocator
     /// </summary>
     public static MemoryAllocator Default { get; } = Create();
 
+    internal long MemoryGroupAllocationLimitBytes { get; private set; } = Environment.Is64BitProcess ?
+        4L * OneGigabyte :
+        OneGigabyte;
+
+    internal int SingleBufferAllocationLimitBytes { get; private set; } = OneGigabyte;
```
Comment (antonfirsov) [inline src/ImageSharp/Memory/Allocators/MemoryAllocator.cs:31]: Actually, there is no good reason to set this to 1GB. Contiguous buffers have a natural limit of `int.MaxValue ~ 2GB` so I think we should set the contiguous limit to `min(int.MaxValue, MemoryAllocatorOptions.AllocationLimitMegabytes * 1MB)`. That would get rid of all obscure logic and make the semantics of `MemoryAllocatorOptions.AllocationLimitMegabytes` very obvious.

Comment (JimBobSquarePants) [reply src/ImageSharp/Memory/Allocators/MemoryAllocator.cs:31]: Yeah. I like that. The only risk we have with this stuff is in our decoders which can be easily mitigated with some care (PNG tweaks)

File: src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs [hunk 2]
```diff
@@ -27,4 +28,22 @@ public struct MemoryAllocatorOptions
             this.maximumPoolSizeMegabytes = value;
         }
     }
+
+    /// <summary>
+    /// Gets or sets a value defining the maximum (discontiguous) buffer size that can be allocated by the allocator in Megabytes.
+    /// <see langword="null"/> means platform default: 1GB on 32-bit processes, 4GB on 64-bit processes.
+    /// </summary>
+    public int? AllocationLimitMegabytes
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs:36]: You got it in the options! Nice!

File: src/ImageSharp/Memory/Allocators/MemoryAllocator.cs [hunk 3]
```diff
@@ -30,16 +40,24 @@ public abstract class MemoryAllocator
...
     /// Creates the default <see cref="MemoryAllocator"/> using the provided options.
     /// </summary>
     /// <param name="options">The <see cref="MemoryAllocatorOptions"/>.</param>
     /// <returns>The <see cref="MemoryAllocator"/>.</returns>
-    public static MemoryAllocator Create(MemoryAllocatorOptions options) =>
-        new UniformUnmanagedMemoryPoolMemoryAllocator(options.MaximumPoolSizeMegabytes);
+    public static MemoryAllocator Create(MemoryAllocatorOptions options)
+    {
+        UniformUnmanagedMemoryPoolMemoryAllocator allocator = new(options.MaximumPoolSizeMegabytes);
+        if (options.AllocationLimitMegabytes.HasValue)
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Memory/Allocators/MemoryAllocator.cs:53]: For V4 I think we should introduce `UniformUnmanagedMemoryPoolOptions` which has the standard options as a property.

File: src/ImageSharp/Memory/InvalidMemoryOperationException.cs [hunk 4]
```diff
@@ -24,4 +26,8 @@ public InvalidMemoryOperationException(string message)
     public InvalidMemoryOperationException()
     {
     }
+
+    [DoesNotReturn]
+    internal static void ThrowAllocationOverLimitException(long length, long limit) =>
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Memory/InvalidMemoryOperationException.cs:31]: I like this sitting here.

File: src/ImageSharp/Memory/Allocators/SimpleGcMemoryAllocator.cs [hunk 5]
```diff
@@ -19,6 +20,13 @@ public override IMemoryOwner<T> Allocate<T>(int length, AllocationOptions option
     {
         Guard.MustBeGreaterThanOrEqualTo(length, 0, nameof(length));
 
+        int lengthInBytes = length * Unsafe.SizeOf<T>();
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Memory/Allocators/SimpleGcMemoryAllocator.cs:23]: For V4 I'd like to have this in `MemoryAllocator` so we don't have to repeat the check.

File: src/ImageSharp/Memory/Allocators/MemoryAllocator.cs [hunk 6]
```diff
@@ -69,10 +87,31 @@ public virtual void ReleaseRetainedResources()
...
     /// <exception cref="InvalidMemoryOperationException">Thrown when 'blockAlignment' converted to bytes is greater than the buffer capacity of the allocator.</exception>
-    internal virtual MemoryGroup<T> AllocateGroup<T>(
+    internal MemoryGroup<T> AllocateGroup<T>(
         long totalLength,
         int bufferAlignment,
         AllocationOptions options = AllocationOptions.None)
         where T : struct
-        => MemoryGroup<T>.Allocate(this, totalLength, bufferAlignment, options);
+    {
+        long totalLengthInBytes = totalLength * Unsafe.SizeOf<T>();
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Memory/Allocators/MemoryAllocator.cs:96]: I think it might be possible to overflow this. I think one of our tests that allocates a 256 byte struct does so.

**Review by JimBobSquarePants — COMMENTED** [review]
That's much neater than my version. I say go with this. 👍

File: src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs (hunk 2 above)
Comment (tocsoft) [inline src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs:36]: Is this consistent with how we talk about memory across the public api? do we talk about megabytes anywhere else in the public api or is it all bytes?

we want to make sure we are being consistent on our units of measure in the public api surface.

Comment (antonfirsov) [reply src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs:36]: The other property on `MemoryAllocatiorOptions` is `MaximumPoolSizeMegabytes`. When I designed the [MemoryAllocator configuration API](https://docs.sixlabors.com/articles/imagesharp/memorymanagement.html#configuring-the-pool-size) it seemed like Megabytes are easier to reason about when talking about limits.

File: src/ImageSharp/Memory/Allocators/MemoryAllocator.cs (hunk 3 above)
Comment (antonfirsov) [reply src/ImageSharp/Memory/Allocators/MemoryAllocator.cs:53]: Actually, `AllocatorOptions` is specific to `UniformUnmanagedMemoryAllocator`. I don't think anyone ever would need another allocator IRL. The design keeps it pluggable just in case + `SimpleGcMemoryAllocator` can be useful for diagnostic purposes since managed allocations are easy to track with standard .NET tools. But `SimpleGcMemoryAllocator` should not be used in production.

To secure users who still use it (mostly legacy code designed to workaround 1.* issues), I applied the default limits, but you cannot configure `SimpleGcMemoryAllocator` with `MemoryAllocatorOptions`.

**Review by JimBobSquarePants — APPROVED** [review]
I'm happy with this @antonfirsov and have created a backport PR for V2.

 I'll wait for your final read-through to merge though.

File: tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs [hunk 7]
```diff
@@ -558,4 +558,16 @@ public void BmpDecoder_CanDecode_Os2BitmapArray<TPixel>(TestImageProvider<TPixel
...
+    [Theory]
+    [WithFile(Issue2696, PixelTypes.Rgba32)]
+    public void BmpDecoder_ThrowsException_Issue2696<TPixel>(TestImageProvider<TPixel> provider)
+        where TPixel : unmanaged, IPixel<TPixel>
+    {
+        InvalidImageContentException ex = Assert.Throws<InvalidImageContentException>(() =>
+            {
+                using Image<TPixel> image = provider.GetImage(BmpDecoder.Instance);
+            });
+        Assert.IsType<InvalidMemoryOperationException>(ex.InnerException);
```
Comment (antonfirsov) [inline tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs:571]: This made me find that the file wasn't the actual file from #2696 here, leading to an exception in header parsing instead of an allocation failure. Fixed in [d1cc651](https://github.com/SixLabors/ImageSharp/pull/2706/commits/d1cc651e19def81df66779985a50f9372db332bc).
