### PR TITLE
Correctly handle identity transforms with varying dimensions

### LINKED ISSUE #1911: ImageProcessingException when resizing an image of similar size to the target.
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Calling the transform processor on an image sometimes throws an exception:

```
SixLabors.ImageSharp.ImageProcessingException
  HResult=0x80131500
  Message=An error occurred when processing the image using AffineTransformProcessor`1. See the inner exception for more detail.
  Source=SixLabors.ImageSharp
  StackTrace:
   at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.ICloningImageProcessor<TPixel>.CloneAndExecute()
   at SixLabors.ImageSharp.Processing.Processors.CloningImageProcessor`1.SixLabors.ImageSharp.Processing.Processors.IImageProcessor<TPixel>.Execute()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.TransformExtensions.Transform(IImageProcessingContext ctx, Rectangle sourceRectangle, Matrix3x2 transform, Size targetDimensions, IResampler sampler)
   at VulcanTest.ImageOperationTest.<>c.<TestImageCrop>b__8_0(IImageProcessingContext x) in C:\Users\MaxE\source\repos\Vulcan\VulcanTest\ImageOperationTest.cs:line 485
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Mutate[TPixel](Image`1 source, Action`1 operation)
   at VulcanTest.ImageOperationTest.TestImageCrop() in C:\Users\MaxE\source\repos\Vulcan\VulcanTest\ImageOperationTest.cs:line 483

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentOutOfRangeException: Parameter "Destination buffer too short!" (System.Int64) must be less than or equal to 14414946, was 14419587 (Parameter 'Destination buffer too short!')
```

I have only seen it happen with this combination of inputs, it seems to be caused by the image being very slightly larger than the destination rectangle.

### Steps to Reproduce

```C#
var image = new Image<Rgba32>(Configuration.Default, 3107, 4641, new Rgba32(30, 35, 36));

image.Metadata.ResolutionUnits = PixelResolutionUnit.PixelsPerInch;
image.Metadata.VerticalResolution = 300;
image.Metadata.HorizontalResolution = 300;

image.Mutate<Rgba32>(x => {
  var imageTransform = new Matrix3x2(1, 0, 0, 1, 0, 0);
  x = x.Transform(new SixLabors.ImageSharp.Rectangle(0, 0, 3106, 4641), imageTransform, new SixLabors.ImageSharp.Size(3106, 4641), new LanczosResampler());
});
```

### System Configuration
- ImageSharp version: >= 1.0.2
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.6.2
- Additional information:

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Fixes #1911 

- Fixes a situation where given source and destination rectangles can cause an `ImageProcessingException` during transforms when an identity matrix is passed.
- Renames ` Buffer2DRegion{T}.GetRowSpan(y)` adding the `Dangerous` prefix to match other implementations. CC @antonfirsov 
- Removes the exception wrapping from the base cloning processor #1827

### CODE REVIEW

File: src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs [hunk 1]
```diff
@@ -61,10 +61,18 @@ public void ApplyTransform<TResampler>(in TResampler sampler)
             Matrix3x2 matrix = this.transformMatrix;
 
             // Handle transforms that result in output identical to the original.
-            if (matrix.Equals(default) || matrix.Equals(Matrix3x2.Identity))
+            // Degenerate matrices are already handled in the upstream definition.
+            if (matrix.Equals(Matrix3x2.Identity))
             {
                 // The clone will be blank here copy all the pixel data over
-                source.GetPixelMemoryGroup().CopyTo(destination.GetPixelMemoryGroup());
+                var interest = Rectangle.Intersect(this.SourceRectangle, destination.Bounds());
```
Comment (antonfirsov) [inline src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs:68]: It looks like the rest of `AffineTransformProcessor<T>` code doesn't respect `SourceRectangle`.

The following two tests have a tiny difference in input matrices, yet they produce very different results after this change in the PR:

```C#
[Theory]
[WithTestPatternImages(100, 100, PixelTypes.Rgba32)]
public void Identity<TPixel>(TestImageProvider<TPixel> provider)
    where TPixel : unmanaged, IPixel<TPixel>
{
    using Image<TPixel> src = provider.GetImage();

    Matrix3x2 m = Matrix3x2.Identity;
    Rectangle r = new Rectangle(25, 25, 50, 50);
    src.Mutate(x => x.Transform(r, m, new Size(100, 100), KnownResamplers.Bicubic));
    src.DebugSave(provider);
}

[Theory]
[WithTestPatternImages(100, 100, PixelTypes.Rgba32)]
public void AlmostIdentity<TPixel>(TestImageProvider<TPixel> provider)
    where TPixel : unmanaged, IPixel<TPixel>
{
    using Image<TPixel> src = provider.GetImage();

    Matrix3x2 m = Matrix3x2.CreateRotation(0.0001f, new Vector2(50, 50));
    Rectangle r = new Rectangle(25, 25, 50, 50);
    src.Mutate(x => x.Transform(r, m, new Size(100, 100), KnownResamplers.Bicubic));
    src.DebugSave(provider);
}
```

Identity:
image

AlmostIdentity:
image


On master they are equally broken not respecting the `SourceRectangle`. It seems like `ProjectiveTransform` suffers from the same issue.

I wonder how to proceed? I see two options:
1. Open a tracking issue & fix the processor
2. Drop `sourceRectangle` the `Transform` overloads, and open a tracking issue to implement them.

Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs:68]: Well caught! I actually thought they we're and I'd just made an oversight. 

I'll actually have a look at the entire implementation and see if it can be a quick fix.

Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs:68]: Fix was easy enough. I've updated two ref files to match correct results but wondering what the best approach for coverage is. I could add refs for the tests you provided and do one using `Matrix4x4.CreateRotationX` for perspective equivalents but would like to avoid more ref images if possible.

**Comment by JimBobSquarePants** [comment]
@antonfirsov I've seen this pop up 2X now. Should we be concerned or is it a simple memory pressure thing driven by the environment.
https://github.com/SixLabors/ImageSharp/runs/4913118322?check_suite_focus=true#step:13:319

**Comment by antonfirsov** [comment]
It should be environmental, will attempt to fix, or at least reduce flakiness by moving it out of process so at least it doesn't race with parallel tests for the same virtual address space.

**Comment by JimBobSquarePants** [comment]
Ace. I'll rerun these anyway to get he green light

File: src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs (hunk 1 above)
Comment (antonfirsov) [reply src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs:68]: More ref images should not cause trouble as long as they are small (a few bigger ones can weight much more than many small ones). We can transform the 30x30 central part of a 60x60 image to keep the output as small as possible.
I would turn `AlmostIdentity` into a theory and test a few more rotation angles. (Eg pi/4 -pi/4) We should see it rotating smoothly and the epsilon rotation should be visually indistinguishable from the special-cased 0 rotation.

Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs:68]: Done

**Review by antonfirsov — APPROVED** [review]
Looks good, well done!
