### PR TITLE
Fix and standardize EXIF dimension transform updates

### LINKED ISSUE #423: "Value should be an unsigned short" exception on image with EXIF rotate.
### Description
The image I want to resize has EXIF and ImageSharp tries to update it with new Width/Height values on rotating.
I have "Value should be an unsigned short" on following code:
```
var input = @"G:\temp\temp-img\1.jpg";
using (var image = SixLabors.ImageSharp.Image.Load(input))
{
       image.Mutate(x => x
            .Rotate((float)90.0)); // Exception goes here
       image.Save(input); 
}
```

### Analytics
Looks like problem in RotateProcessor
```
 profile.SetValue(ExifTag.PixelXDimension, source.Width);
```
It expects source.Width as `ushort`, but Image.Width defined as `int`:  
`public int Width => this.frames.RootFrame.Width;`

image

image

My suggestion is to cast PixelXDimension from int to ushort. It fixes problem but I'm not sure it is the best solution.

### Steps to Reproduce

Use 1.jpg attached and try to rotate it.

### System Configuration

- ImageSharp version: 1.0.0-dev000621   1.0.0-beta0002   
- Other ImageSharp packages and versions: master(6f438dac852c5d7408161e1afa034984671257f4)
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 2.0
- Additional information:

### Exception: 

```
System.ArgumentException occurred
  HResult=0x80070057
  Message=Value should be an unsigned short.
Parameter name: value
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at SixLabors.ImageSharp.Guard.IsTrue(Boolean target, String parameterName, String message) in G:\ext\xxxxx\ImageSharp\src\ImageSharp\Common\Helpers\Guard.cs:line 212
```

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
This PR introduces a helper method and base class to ensure that any EXIF dimensional metadata values are correctly updates should the dimensions of the image change. Fixes #423 and supersedes #424

### CODE REVIEW

File: src/ImageSharp/Processing/Transforms/TransformHelpers.cs [hunk 1]
```diff
@@ -12,6 +14,38 @@ namespace SixLabors.ImageSharp
     /// </summary>
     internal class TransformHelpers
     {
+        /// <summary>
+        /// Updates the dimensional metadata of a transformed image
+        /// </summary>
+        /// <typeparam name="TPixel">The pixel format.</typeparam>
+        /// <param name="image">The image to update</param>
+        public static void UpdateDimensionalMetData<TPixel>(Image<TPixel> image)
```
Comment (dlemstra) [inline src/ImageSharp/Processing/Transforms/TransformHelpers.cs]: Looks like you are missing an `a` here.

File: src/ImageSharp/DefaultInternalImageProcessorContext.cs [hunk 2]
```diff
@@ -52,8 +52,8 @@ public IImageProcessingContext<TPixel> ApplyProcessor(IImageProcessor<TPixel> pr
             if (!this.mutate && this.destination == null)
             {
                 // This will only work if the first processor applied is the cloning one thus
-                // realistically for this optermissation to work the resize must the first processor
-                // applied any only up processors will take the douple data path.
+                // realistically for this optimization to work the resize must the first processor
```
Comment (dlemstra) [inline src/ImageSharp/DefaultInternalImageProcessorContext.cs]: 👍

File: src/ImageSharp/Processing/Transforms/TransformHelpers.cs (hunk 1 above)
Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Transforms/TransformHelpers.cs]: Where? Am I being blind?

Comment (dlemstra) [reply src/ImageSharp/Processing/Transforms/TransformHelpers.cs]: `UpdateDimensionalMetData`
`UpdateDimensionalMetaData`

Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Transforms/TransformHelpers.cs]: Dammit! :smile:
