### PR TITLE
Use GreatestCommonDivisor to prevent overflow

### LINKED ISSUE #1616: Overflow in `LeastCommonMultiple` leads to exception during resize operation
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When doing a resize operation of an image with a particularly large height, I got an exception that ImageSharp was trying to allocate memory of negative total length.  I tracked this down to this line where period is calculated. The period calculation overflows making period become negative which ends up failing when it creates the kernel map several line below (158) while allocating memory in the constructor.
https://github.com/SixLabors/ImageSharp/blob/a6c17854684edaa998080233273d19d987174bb5/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.cs#L135

One possible solution for this particular case could be to change that line to use greatest common divisor instead and calculate period using:
```csharp
int period = destinationSize / Numerics.GreatestCommonDivisor(sourceSize, destinationSize);
```

### Steps to Reproduce
With a height of 207773, and a destination height of 51943, the GCD is 1 causing an overflow when multiplying both of those numbers in `Numerics.LeastCommonMultiple(a, b)`.
```csharp
var width = 5000;
var height = 207773;
using (var img = new Image<L16>(width, height))
{
    using var clone = img.Clone(ctx =>
    {
        var factor = 4;
        ctx.Resize(img.Width / factor, img.Height / factor, KnownResamplers.Bicubic);
    });
}
```

### System Configuration
I don't think it's relevant.

- ImageSharp version: 1.0.3
- Other ImageSharp packages and versions: N/A
- Environment (Operating system, version and so on): Win 10
- .NET Framework version: NET 3.1, NET 5.0
- Additional information: N/A

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Fixes #1616
Updates the period calculation to use `GreatestCommonDivisor` as per issue.

### CODE REVIEW

File: src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.cs [hunk 1]
```diff
@@ -130,9 +130,9 @@ protected virtual void Dispose(bool disposing)
             int radius = (int)TolerantMath.Ceiling(scale * sampler.Radius);
 
             // 'ratio' is a rational number.
-            // Multiplying it by LCM(sourceSize, destSize)/sourceSize will result in a whole number "again".
+            // Multiplying it by destSize/GCD(sourceSize, destSize) will result in a whole number "again".
             // This value is determining the length of the periods in repeating kernel map rows.
-            int period = Numerics.LeastCommonMultiple(sourceSize, destinationSize) / sourceSize;
+            int period = destinationSize / Numerics.GreatestCommonDivisor(sourceSize, destinationSize);
```
Comment (dlemstra) [inline src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.cs:135]: Cannot place a comment on line `122` but do we need to protect this method from division by zero?

Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.cs:135]: GCD should always yield a positive integer unless both inputs are 0. That can never happen in our code since the `ResizeHelper` will always return positive integers.

**Review by antonfirsov — APPROVED** [review]
LGTM
