### PR TITLE
Ensure min dimension of 1px following rounding.

### LINKED ISSUE #1195: Images 2 pixels wide can not be resized
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When trying to resize an image that's 2px wide or less a `ArgumentOutOfRangeException` is thrown with the message: `Parameter "width" (System.Int32) must be greater than 0, was 0`.

This happens at 1 pixels and 2 pixels, but not 3 pixels. Practically speaking this probably won't matter in most scenarios but I thought I'd let you guys know.

### Steps to Reproduce
This code snippet will repro:

```
var memoryStream = new MemoryStream(File.ReadAllBytes("player-min-px.jpg"));
using (var image = Image.Load(memoryStream))
{
    var size = new Size(50, 50);
    image.Mutate(x => x
        .Resize(
            new ResizeOptions
            {
                Size = size,
                Mode = ResizeMode.Max
            }));
}
```

### System Configuration
- ImageSharp version: 1.0.0-rc0001
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: Dotnet Core 2.2

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

When calculating a target size/rectangle during resizing ensure that rounding doesn't leave a width/height of zero. Fixes #1195

### CODE REVIEW

File: src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs [hunk 1]
```diff
@@ -419,9 +419,14 @@ public static (Size, Rectangle) CalculateTargetLocationAndBounds(Size sourceSize
             int targetHeight = targetRectangle.Height > 0 ? targetRectangle.Height : height;
 
             // Target image width and height can be different to the rectangle width and height.
-            return (new Size(width, height), new Rectangle(targetX, targetY, targetWidth, targetHeight));
+            return (new Size(Sanitize(width), Sanitize(height)), new Rectangle(targetX, targetY, Sanitize(targetWidth), Sanitize(targetHeight)));
         }
 
         private static void ThrowInvalid(string message) => throw new InvalidOperationException(message);
+
+        private static int Sanitize(int input)
```
Comment (dlemstra) [inline src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs:427]: Nitpicking but this could be an array.

File: src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs [hunk 2]
```diff
@@ -72,7 +72,7 @@ public static (Size, Rectangle) CalculateTargetLocationAndBounds(Size sourceSize
 
                 // case ResizeMode.Stretch:
                 default:
-                    return (new Size(width, height), new Rectangle(0, 0, width, height));
+                    return (new Size(Sanitize(width), Sanitize(height)), new Rectangle(0, 0, width, height));
```
Comment (dlemstra) [inline src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs:75]: Do we not need to sanatize the second width and height?

Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs:75]: Yeah, missed that with my find/replace

File: src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs (hunk 1 above)
Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs]: I'm usually not precious, updated now though
