### PR TITLE
Fix for B&W pbm images with width not dividable by 8

### LINKED ISSUE #2477: Images saved using Pbm Binary Byte format (P4) are corrupted.
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

3.0.1

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

6.0

### Description

Images saved using Pbm Binary Byte format (P4) are corrupted. 
It seems like the file written is too short and if you try to open it in GIMP it will say it's corrupted.
Reloading the saved file and saving to a different format you can see it is visibly corrupted. 
I have tried a few different images and they all have the same issue. 

### Steps to Reproduce

`
var image = Image.Load("input.png");
var encoder = new PbmEncoder()
{
    ColorType = PbmColorType.BlackAndWhite,
    ComponentType = PbmComponentType.Byte,
    Encoding = PbmEncoding.Binary
};
image.Save("output.pbm", encoder);
var output = Image.Load("output.pbm");
output.SaveAsPng("output.png");

`

### Images

input
output
[output.zip](https://github.com/SixLabors/ImageSharp/files/11785960/output.zip)
[outputImageMagick.zip](https://github.com/SixLabors/ImageSharp/files/11786038/outputImageMagick.zip)

### PR DESCRIPTION
**Pull request by ynse01**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
This fixes #2477 by handling Black & White binary images with a width not dividable by 8 correctly. The handling of the padding bits was incorrect and not according to the specification.

Thanks for reporting this bug !

### CODE REVIEW

File: src/ImageSharp/Formats/Pbm/BinaryDecoder.cs [hunk 1]
```diff
@@ -162,23 +161,12 @@ private static void ProcessBlackAndWhite<TPixel>(Configuration configuration, Bu
             for (int x = 0; x < width;)
             {
                 int raw = stream.ReadByte();
-                int bit = startBit;
-                startBit = 0;
-                for (; bit < 8; bit++)
+                int stopBit = Math.Min(8, width - x);
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Formats/Pbm/BinaryDecoder.cs:164]: Should be a nice perf boost here also.

**Comment by JimBobSquarePants** [comment]
Thanks so much for doing this @ynse01 !

The code looks great, however it doesn't look like the reference image was included in GIT LFS for some reason. 

```basjh
git lfs track --filename [file path]
```
Should do the trick.

I'd do it for you, but LFS doesn't work well with GitHub when pushing a file against a fork.

File: src/ImageSharp/Formats/Pbm/BinaryDecoder.cs (hunk 1 above)
Comment (ynse01) [reply src/ImageSharp/Formats/Pbm/BinaryDecoder.cs:164]: Indeed, solving a bug by simplifying the code

**Comment by ynse01** [comment]
> I'd do it for you, but LFS doesn't work well with GitHub when pushing a file against a fork.

Please do so, as I tried the command and as a result I got modification in the _.gitattributes_ file as a result. Doesn't look desirable, as the file extensions are already mentioned, so I didn't commit those modifications.

**Comment by JimBobSquarePants** [comment]
I just pulled your branch down and cut the file to see what git was saying. It looks like the GitHub UI was playing silly buggers because the image is definitely already tracked.

image

This looks great then. Thanks for your help!

**Review by JimBobSquarePants — APPROVED** [review]
