### PR TITLE
Gif decoder. Fix memory access violations.

### LINKED ISSUE #2012: Fail to Load a Gif Image with v2.0.0 but works with v1.0.4 on the same machine.
### ImageSharp version

2.0.0

### Other ImageSharp packages and versions

1.0.4

### Environment (Operating system, version and so on)

Windows 10

### .NET Framework version

.NET 5

### Description

I came across a gif image https://www.muhammadniaz.net/wp-content/uploads/2013/06/Stronghold-Crusader-Extreme-Cover.gif which loaded correctly with ImageSharp v1.0.4 but failed with v2.0.0 with an unmanaged exception which cannot be caught by the try-catch

### Steps to Reproduce

```#
try
{
    var client = new HttpClient();
    string url = "https://www.muhammadniaz.net/wp-content/uploads/2013/06/Stronghold-Crusader-Extreme-Cover.gif";
    var bytes = await client.GetByteArrayAsync(url);
    var image = SixLabors.ImageSharp.Image.Load(bytes, out var format);
    Console.WriteLine(format);
}
catch (Exception e)
{
    Console.WriteLine(e.Message);
    Console.WriteLine(e.StackTrace);
    Debugger.Break();
}
```

### Images

Stronghold-Crusader-Extreme-Cover

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #2012

- Fixes `GifXmpApplicationExtension` by using a more robust (_handles empty profiles_) and less allocation heavy reader.
- Provides protection against invalid memory operations in `LzwDecoder`
- Fixes cloning of `XmpProfile` when cloning `ImageMetadata`

Integrity of reencoded metadata has been tested externally using ExifTools

### CODE REVIEW

File: src/ImageSharp/Formats/Gif/Sections/GifXmpApplicationExtension.cs [hunk 1]
```diff
@@ -67,7 +53,7 @@ public int WriteTo(Span<byte> buffer)
             int totalSize = this.ContentLength;
             if (buffer.Length < totalSize)
             {
-                throw new InsufficientMemoryException("Unable to write XMP metadata to GIF image");
+                ThrowInsufficientMemory();
```
[the remark this answers is not in the document]
Comment (JimBobSquarePants) [reply src/ImageSharp/Formats/Gif/Sections/GifXmpApplicationExtension.cs:56]: Yeah that’s an odd one. It could only ever be triggered if somehow the extension content length was incorrect which is impossible since we own the property. I’m gonna remove it.

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs [hunk 2]
```diff
@@ -254,5 +263,8 @@ public void Dispose()
             this.suffix.Dispose();
             this.pixelStack.Dispose();
         }
+
+        [MethodImpl(InliningOptions.ColdPath)]
+        public static void ThrowBadMinimumCode() => throw new InvalidImageContentException("Gif Image does not contain a valid LZW minimum code.");
```
Comment (brianpopow) [inline src/ImageSharp/Formats/Gif/LzwDecoder.cs:268]: Maybe this should be in `GifThrowHelper`?

**Review by brianpopow — APPROVED** [review]
Looks good

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs (hunk 2 above)
Comment (JimBobSquarePants) [reply src/ImageSharp/Formats/Gif/LzwDecoder.cs:268]: Yeah, forgot about that class will move
