### PR TITLE
Fix Png Encoder Compression

### LINKED ISSUE #1027: PNG Encoder produces too huge images and different sizes in Linux and Windows
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When saving an image to PNG I end up with a file that is more than 5x larger than what I would obtain by using **System.Drawing** (or **Paint.NET**)
Attached are the images I generated using **ImageSharp**, and the same one opened/saved with **Paint.NET**.
I've tried to tweak the `CompressionLevel` and `FilterMethod` (not so sure what this one is about) 
properties of the encoder, but this changes nearly nothing in the output image size:
* Compression levels of 1 to 5 give me the same size of 310 KB both in my Windows and WSL tests
* Compression levels of 6 to 9 give me a size of 289 KB when run on Windows but 102 KB in WSL
*  With `FilterMethod` set to `Adaptive`, I obtain slightly better results; however, far from my expected 55 KB

I can see there's a related issue (#702); however, regardless of the different output sizes in Linux vs Windows, I still think my issue stands as a bug as I'd very much like to be able to obtain a ~50 KB image instead of 300 KB.

### Steps to Reproduce

Here is the code I used to exhibit this behavior:

```csharp
using System.IO;
using System.Runtime.InteropServices;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Png;
using SixLabors.ImageSharp.PixelFormats;

namespace ImageSharpCompressionTest
{
    internal sealed class Program
    {
        private static void Main(string[] args)
        {
            var encoder = new PngEncoder
            {
                BitDepth = PngBitDepth.Bit8,
                ColorType = PngColorType.RgbWithAlpha
            };

            // encoder.FilterMethod = PngFilterMethod.Adaptive;

            var w = 3500;
            var h = 3500;
            var rgbaBytes = GetImageBytes(w, h);

            var rootdir = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? @"c:\temp\win" : "/mnt/c/temp/lnx/";
            if (!Directory.Exists(rootdir)) Directory.CreateDirectory(rootdir);

            using (var image = Image.LoadPixelData<Rgba32>(rgbaBytes, w, h))
            {
                for (var level = 1; level <= 9; level++)
                {
                    encoder.CompressionLevel = level;

                    var filename = Path.Combine(rootdir, $"compress-{level}.png");
                    using (var stream = File.Create(filename))
                        image.SaveAsPng(stream, encoder);
                }
            }
        }

        private static byte[] GetImageBytes(int width, int height)
        {
            var bytes = new byte[width * height * 4];
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < width * 4; x += 4)
                {
                    bytes[4 * y * width + x] = (byte)((x + y) % 256); // R
                    bytes[4 * y * width + x + 1] = 0; // G
                    bytes[4 * y * width + x + 2] = 0; // B
                    bytes[4 * y * width + x + 3] = 255; // A
                }
            }

            return bytes;
        }
    }
}
```

Attachments:

* Running in WSL: [lnx.zip](https://github.com/SixLabors/ImageSharp/files/3728324/lnx.zip)
* Running on Windows: [win.zip](https://github.com/SixLabors/ImageSharp/files/3728325/win.zip)
* Opened/Saved by Paint.NET: compress-pdn

### System Configuration

- ImageSharp version: **1.0.0-beta0007**
- Other ImageSharp packages and versions: none explicitly added
- Environments: 
  - Windows 10 Pro 1709 (French)
  - Ubuntu 18.04 WSL
- .NET Framework versions: 
  - Windows .NET Core 3.0.100 (but still running a netcoreapp2.2)
  - Linux .NET Core 2.2.204
- Additional information:

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Replaces the .NET `DeflateStream` implementation used by the png encoder with a fully managed one ported from SharpZipLib and heavily modified. 

This fixes #1027 with a 6x improvement in compression with the supplied image.

Benchmarks are.... ok I guess.... I managed to make the ported `DeflaterOuputStream` and accompanying classes around 40% faster but we've lost a fair amount of performance compared to the native SIMD accelerated version used by .NET Core. I think the massive compression gains are worth it though but if anyone fancies a crack at further optimization please give it a go.

#### Before

|               Method |  Job | Runtime | LargeImage |     Mean |     Error |    StdDev | Ratio | RatioSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|--------------------- |----- |-------- |----------- |---------:|----------:|----------:|------:|--------:|---------:|---------:|---------:|----------:|
| 'System.Drawing Png' |  Clr |     Clr |      False | 16.00 ms |  1.429 ms | 0.0783 ms |  1.00 |    0.00 | 500.0000 | 218.7500 | 218.7500 |   2.03 MB |
|     'ImageSharp Png' |  Clr |     Clr |      False | 31.80 ms |  2.094 ms | 0.1148 ms |  1.99 |    0.01 | 500.0000 | 500.0000 | 500.0000 |   2.25 MB |
|                      |      |         |            |          |           |           |       |         |          |          |          |           |
| 'System.Drawing Png' | Core |    Core |      False | 16.85 ms | 10.899 ms | 0.5974 ms |  1.00 |    0.00 | 500.0000 | 218.7500 | 218.7500 |   2.03 MB |
|     'ImageSharp Png' | Core |    Core |      False | 21.19 ms |  7.654 ms | 0.4195 ms |  1.26 |    0.07 | 562.5000 | 531.2500 | 531.2500 |   2.24 MB |

#### After

|               Method |  Job | Runtime | LargeImage |     Mean |    Error |    StdDev | Ratio | RatioSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|--------------------- |----- |-------- |----------- |---------:|---------:|----------:|------:|--------:|---------:|---------:|---------:|----------:|
| 'System.Drawing Png' |  Clr |     Clr |      False | 18.15 ms | 4.199 ms | 0.2302 ms |  1.00 |    0.00 | 500.0000 | 218.7500 | 218.7500 |   2.03 MB |
|     'ImageSharp Png' |  Clr |     Clr |      False | 43.28 ms | 1.944 ms | 0.1066 ms |  2.38 |    0.03 | 416.6667 | 416.6667 | 416.6667 |    2.3 MB |
|                      |      |         |            |          |          |           |       |         |          |          |          |           |
| 'System.Drawing Png' | Core |    Core |      False | 18.33 ms | 2.518 ms | 0.1380 ms |  1.00 |    0.00 | 500.0000 | 218.7500 | 218.7500 |   2.03 MB |
|     'ImageSharp Png' | Core |    Core |      False | 43.05 ms | 5.185 ms | 0.2842 ms |  2.35 |    0.03 | 416.6667 | 416.6667 | 416.6667 |    2.3 MB |

### CODE REVIEW

File: src/ImageSharp/Formats/Png/Zlib/DeflaterEngine.cs [hunk 1]
```diff
@@ -0,0 +1,853 @@
...
+        /// </para>
+        /// <para>
+        /// Preconditions:
+        /// <code>
+        /// strstart + DeflaterConstants.MAX_MATCH &lt;= window.length.</code>
+        /// </para>
+        /// </summary>
+        /// <param name="curMatch">The current match.</param>
+        /// <returns>True if a match greater than the minimum length is found</returns>
+        private bool FindLongestMatch(int curMatch)
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Formats/Png/Zlib/DeflaterEngine.cs]: This appears to be a hotspot according to dotTrace. 

image

**Comment by JimBobSquarePants** [comment]
I've done my best. Get stuck in please.

**Comment by JimBobSquarePants** [comment]
I think I'm going to go ahead and merge this. It isn't slow and we get good compression. Any other gains we can make down the line.
