### PR TITLE
Workaround GC.GetMemoryInfo() ARM32 issue

### LINKED ISSUE #2001: Default MemoryAllocator creation crashes on Raspberry Pi OS 11
### ImageSharp version

2.0.0.0

### Other ImageSharp packages and versions

None

### Environment (Operating system, version and so on)

Raspberry Pi OS 11 - Bullseye - 5.10.92.7

### .NET Framework version

6.0.1

### Description

A memory allocation error during Image.Load() when running on Raspberry Pi OS 11 Bullseye 5.10.92

Note that the same code works without error on Raspberry Pi OS 10 Buster 5.10.63.

Version 1 of ImageSharp works OK on both OS versions.

As ImageSharp only processes that one image periodically I also tried globally fixing the MaximumPoolSizeMegabytes to 1 MB, this made no difference.

### Steps to Reproduce

Simply calling...
```using var bmp = Image.Load<Rgba32>("./web/MoonBaseImage.png");```

gives...
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SixLabors.ImageSharp.Memory.MemoryAllocator' threw an exception.
 ---> System.OverflowException: Arithmetic operation resulted in an overflow.
   at SixLabors.ImageSharp.Memory.Internals.UniformUnmanagedMemoryPool..ctor(Int32 bufferLength, Int32 capacity, TrimSettings trimSettings)
   at SixLabors.ImageSharp.Memory.UniformUnmanagedMemoryPoolMemoryAllocator..ctor(Int32 sharedArrayPoolThresholdInBytes, Int32 poolBufferSizeInBytes, Int64 maxPoolSizeInBytes, Int32 unmanagedBufferSizeInBytes, TrimSettings trimSettings)
   at SixLabors.ImageSharp.Memory.UniformUnmanagedMemoryPoolMemoryAllocator..ctor(Int32 sharedArrayPoolThresholdInBytes, Int32 poolBufferSizeInBytes, Int64 maxPoolSizeInBytes, Int32 unmanagedBufferSizeInBytes)
   at SixLabors.ImageSharp.Memory.UniformUnmanagedMemoryPoolMemoryAllocator..ctor(Int32 poolBufferSizeInBytes, Int64 maxPoolSizeInBytes, Int32 unmanagedBufferSizeInBytes)
   at SixLabors.ImageSharp.Memory.UniformUnmanagedMemoryPoolMemoryAllocator..ctor(Nullable`1 maxPoolSizeMegabytes)
   at SixLabors.ImageSharp.Memory.MemoryAllocator.Create()
   at SixLabors.ImageSharp.Memory.MemoryAllocator..cctor()
   --- End of inner exception stack trace ---
   at SixLabors.ImageSharp.Configuration..ctor(IConfigurationModule[] configurationModules)
   at SixLabors.ImageSharp.Configuration.CreateDefaultInstance()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at SixLabors.ImageSharp.Configuration..cctor()
   --- End of inner exception stack trace ---
   at SixLabors.ImageSharp.Configuration.get_Default()
   at SixLabors.ImageSharp.Image.Load[TPixel](String path)
   at CumulusMX.MoonriseMoonset.CreateMoonImage(Double phaseAngle, Double latitude, Int32 size, Boolean transparent) in C:\Code\CumulusMX-Core6\CumulusMX\MoonriseMoonSet.cs:line 1530
   at CumulusMX.Cumulus.DoMoonImage() in C:\Code\CumulusMX-Core6\CumulusMX\Cumulus.cs:line 2665
   at CumulusMX.Cumulus.Initialise(Int32 HTTPport, Boolean DebugEnabled, String startParms) in C:\Code\CumulusMX-Core6\CumulusMX\Cumulus.cs:line 1283
   at CumulusMX.Program.RunAsAConsole(Int32 port, Boolean debug) in C:\Code\CumulusMX-Core6\CumulusMX\Program.cs:line 320
   at CumulusMX.Program.Main(String[] args) in C:\Code\CumulusMX-Core6\CumulusMX\Program.cs:line 271
   at CumulusMX.Program.<Main>(String[] args)
```

If I catch the Image.Load() error and bypass the image processing completely, then a short while later whist the program is running I get another exception...
```
Unhandled exception. System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at SixLabors.ImageSharp.Memory.Internals.UniformUnmanagedMemoryPool.TrimAll(UnmanagedMemoryHandle[] buffersLocal)
   at SixLabors.ImageSharp.Memory.Internals.UniformUnmanagedMemoryPool.Finalize()
```

### PR DESCRIPTION
**Pull request by antonfirsov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Workaround dotnet/runtime#65466 by using the constant fallback pool size if negative memory is reported.

Fixes #2001.

### CODE REVIEW

File: src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs [hunk 1]
```diff
@@ -74,6 +74,10 @@ public UniformUnmanagedMemoryPoolMemoryAllocator(int? maxPoolSizeMegabytes)
             this.nonPoolAllocator = new UnmanagedMemoryAllocator(unmanagedBufferSizeInBytes);
         }
 
+        // This delegate allows overriding the method returning the available system memory,
+        // so we can test our workaround for https://github.com/dotnet/runtime/issues/65466
+        internal static Func<long> GetTotalAvailableMemoryBytes { get; set; } = () => GC.GetGCMemoryInfo().TotalAvailableMemoryBytes;
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs:79]: You're missing a condition here.

#if NETCOREAPP3_1_OR_GREATER

Comment (JimBobSquarePants) [reply src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs:79]: @antonfirsov I've pushed the fix.

Comment (antonfirsov) [reply src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs:79]: I missed the comment and also pushed it 🙈

Comment (JimBobSquarePants) [reply src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs:79]: Doubled fixed now then. We know it's good 😄

**Review by JimBobSquarePants — APPROVED** [review]
