### PR TITLE
Use more accurate bit for alpha lookup.

### LINKED ISSUE #2469: Unexpected artefacts when quantizing images
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.0.1

### Other ImageSharp packages and versions

NA

### Environment (Operating system, version and so on)

Windows, Linux

### .NET Framework version

6

### Description

We are currently experiencing strange artifacts when quantizing images.

### Steps to Reproduce

Load image.
Quantize the image using KnownQuantizers.Wu
The saved output will have unexpected artifacts.

Below is a test program I created to replicate the problem. It does not happen on all images only on some. I have attached a image that it happens on. If you compare the original to the quantized version you will note a grey triangular artifact from right of centre to the right middle of the image.

```
using SixLabors.ImageSharp.Formats.Png;

using (var i = Image.Load("Orig.png"))
{
    i.Mutate(x => x.Quantize(KnownQuantizers.Wu));
    await i.SaveAsPngAsync("Resized.png", new PngEncoder()
    {
        CompressionLevel = PngCompressionLevel.BestCompression,
    });
}
```
Original Image
Orig
Quantized Image
Resized

### Images

Orig
Resized

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Fixes #2469 

Our pixel map accuracy wasn't good enough for alpha comparison, so we were leaving artifacts.

This increases memory from 2.26MB to 4.45MB but not only do we fix our issue, as a result of the increased accuracy, we're also getting less collisions in our RGB components.

### CODE REVIEW

File: src/ImageSharp/Processing/Processors/Quantization/EuclideanPixelMap{TPixel}.cs [hunk 1]
```diff
@@ -149,13 +149,13 @@ private static int DistanceSquared(Rgba32 a, Rgba32 b)
...
     /// providing enough match accuracy.
-    /// Entry count is currently limited to 1185921 entries (2371842 bytes ~2.26MB).
+    /// Entry count is currently limited to 2335905 entries (4671810 bytes ~4.45MB).
     /// </para>
     /// </remarks>
     private unsafe struct ColorDistanceCache : IDisposable
     {
         private const int IndexBits = 5;
-        private const int IndexAlphaBits = 5;
+        private const int IndexAlphaBits = 6;
```
Comment (antonfirsov) [inline src/ImageSharp/Processing/Processors/Quantization/EuclideanPixelMap{TPixel}.cs:158]: This could be zero when `TPixel` doesn't have an alpha. It might be worth to eventually implement some trick to have two versions of EuclideanPixelMap, so we save memory when working with RGB pngs and gifs.

Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Processors/Quantization/EuclideanPixelMap{TPixel}.cs:158]: Good point. We could easily preserve much more accurate matches in less space.
