### PR TITLE
Ensure seekable streams can be read multiple times.

### LINKED ISSUE #2259: Loading image from a stream doesn't start at the current position
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

2.1.3

### Other ImageSharp packages and versions

n/a

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

6.0.0

### Description

I have a file that consists of two concatenated images (ie one PNG file, and then a second PNG file).

When I load the first image, the position of the stream increases, but the second read reads from the beginning again. So, now matter how times I load an image, it's always the first image in the stream that gets loaded.

Here's my sample code:

```
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats.Png;


//var config = new Configuration(new PngConfigurationModule());
//config.ReadOrigin = ReadOrigin.Current; // this makes no difference

//first of all, read the stream sequentially

using var stream = new FileStream("red_and_blue.png", FileMode.Open, FileAccess.Read);

using var i = Image.Load(stream);

Console.WriteLine($"Stream position: {stream.Position}");

using var j = Image.Load(stream);
Console.WriteLine($"Stream position: {stream.Position}"); // THIS HASN'T MOVED

using var i2 = i.CloneAs<Rgb24>();
using var j2 = j.CloneAs<Rgb24>();

Console.WriteLine($"First colour: {i2[5, 5]}");

Console.WriteLine($"Second colour: {j2[5, 5]}"); // THIS SHOULD BE DIFFERENT

//instead, copy the rest of the stream

using var reader = new BinaryReader(stream);
var bytes = reader.ReadBytes((int)(stream.Length - stream.Position));
using var k = Image.Load(bytes);

using var k2 = k.CloneAs<Rgb24>();
Console.WriteLine($"Second colour (2nd attempt): {k2[5, 5]}"); 
```

### Steps to Reproduce

See above

### Images

The final image is made by running:

`copy /b red.png+blue.png red_and_blue.png`

blue
red
red_and_blue

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

Fixes #2259 

I wasn't able to replicate the issue with main in synchronous loading (likely due to the decoder refactor) but I was able to do so for our asynchronous load.

I addition I've included a more efficient fix for buffered stream position setting.

### CODE REVIEW

File: src/ImageSharp/IO/BufferedReadStream.cs [hunk 1]
```diff
@@ -140,7 +141,7 @@ public override int ReadByte()
 
         // Our buffer has been read.
         // We need to refill and start again.
-        if (this.readBufferIndex > this.maxBufferIndex)
+        if (this.readBufferIndex < 0 || this.readBufferIndex > this.maxBufferIndex)
```
Comment (gfoidl) [inline src/ImageSharp/IO/BufferedReadStream.cs:144]:
```suggestion
        if ((uint)this.readBufferIndex > (uint)this.maxBufferIndex)
```
Saves one comparison, as with the uint-cast negative value will be re-interpreted as values > int.MaxValue.

I know this is for streams, so the cost of reading from the stream will be dominant, but I can't stop squeezing out perf 😉

File: src/ImageSharp/IO/BufferedReadStream.cs [hunk 2]
```diff
@@ -186,7 +172,7 @@ public override int Read(Span<byte> buffer)
 
         // Too big for remaining buffer but less than entire buffer length
         // Copy to buffer then read from there.
-        if (count + this.readBufferIndex > this.BufferSize)
+        if (this.readBufferIndex < 0 || (count + this.readBufferIndex > this.BufferSize))
```
Comment (gfoidl) [inline src/ImageSharp/IO/BufferedReadStream.cs:175]: The `+` could overflow (at least in theory).
```suggestion
        if (this.readBufferIndex < 0 || (this.readBufferIndex > this.BufferSize - count))
```
Or to remove one check
```suggestion
        if ((uint)this.readBufferIndex > (uint)(this.BufferSize - count))
```

Comment (JimBobSquarePants) [reply src/ImageSharp/IO/BufferedReadStream.cs]: Should have committed the second one. Will do so later. Thanks!
