### PR TITLE
Decode Jpeg into Rgb24 when pixel type not specified

### LINKED ISSUE #1121: Speed up JPEG Decoder color conversion
Let's finally beat System.Drawing on the JPEG Load->Resize->Save scenario!

As discussed in #1064, it's finally possible thanks to the Intel SIMD intrinsics in .NET Core 3.1. Opening an issue so we can track this work, and hopefully get some help & feedback from the community.

/cc @Sergio0694 @saucecontrol

# Current pipeline
Summary of steps currently done  by [`ConvertColorsInto`](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegImagePostProcessor.cs#L145):

**[D]:** Data representation
*(T):* Bulk transformation between data representations

### (case a) Y+Cb+Cr planes --> Single `Rgba32` buffer
|         |  |
| ------- | :--- |
| **[D]** | **3 Planes of W\*H sized `float` jpeg color channels normalized to 0-255 (3 x `Buffer2D<float>`, Y+Cb+Cr)** |
|  *(T)*  | *[Color convert](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrSimdAvx2.cs#L77) and [pack](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrSimdAvx2.cs#L105) into a single `Vector4` buffer* |
| **[D]** | **Floating point RGBA data as `Memory<Vector4>`** |
|  *(T)*  | *Convert the `Vector4` buffer to an `Rgba32` buffer. In the `Rgba32` case case, the input buffer could be handled as homogenous `float` buffer, where all individual `float` values should be converted to `byte`-s. The conversion is implemented in [`BulkConvertNormalizedFloatToByteClampOverflows`](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Common/Helpers/SimdUtils.ExtendedIntrinsics.cs#L137), utilizing AVX2 conversion and narrowing operations through `Vector<T>`* |
| **[D]** | **The result image as an `Rgba32` buffer** |

### (case b) Y+Cb+Cr planes --> Single `Rgb24` buffer
|         |  |
| ------- | :--- |
| **[D]** | **3 Planes of W\*H sized `float` jpeg color channels normalized to 0-255 (3 x `Buffer2D<float>`, Y+Cb+Cr)** |
|  *(T)*  | *[Color convert](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrSimdAvx2.cs#L77) and [pack](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrSimdAvx2.cs#L105) into a single `Vector4` buffer* |
| **[D]** | **Floating point RGBA data as `Memory<Vector4>`** |
|  *(T)*  | *Convert the `Vector4` buffer to an `Rgba32` buffer, utilizing [`BulkConvertNormalizedFloatToByteClampOverflows`](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Common/Helpers/SimdUtils.ExtendedIntrinsics.cs#L137), utilizing AVX2 conversion and narrow operations through `Vector<T>`* |
| **[D]** | **[Temporary `Rgba32` buffer](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/PixelFormats/Utils/Vector4Converters.RgbaCompatible.cs#L106)** |
|  *(T)*  | *[`PixelOperations<Rgb24>.FromRgba32()`](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/PixelFormats/PixelOperations%7BTPixel%7D.Generated.cs#L451) (sub-optimal, extra transformation!)* |
| **[D]** | **The result image as an `Rgb24` buffer** |

# Optimized pipeline

### (default `Rgb24` case) Y+Cb+Cr planes --> Single `Rgb24` buffer
|         | |
| ------- | :--- |
| **D1** | **3 Planes of W\*H sized `float` jpeg color channels normalized to 0-255 (3 x `Buffer2D<float>`, Y+Cb+Cr)** |
|  *(T)*  | *Color convert, the 3 planes, and write them back to the originating buffers* |
| **D2** | **3 Planes of `Buffer2D<float>`, R+G+B)** |
|  *(T)*  | *Narrow the `float` buffers to `byte` buffers using `SimdUtils.BulkConvertNormalizedFloatToByteClampOverflows`* |
| **D3** | **3 Planes of `Buffer2D<byte>`, R+G+B** |
|  *(T)*  | *PACK the separate image planes (color channels) into a single `Rgb24` buffer* |
| **D4** | **The result image as an `Rgb24` buffer** |

### (`TPixel` case) Y+Cb+Cr planes --> Single `TPixel` buffer
|         | |
| ------- | :--- |
| **D1** | **3 Planes of W\*H sized `float` jpeg color channels normalized to 0-255 (3 x `Buffer2D<float>`, Y+Cb+Cr)** |
|  *(T)*  | *All the steps from the default `Rgb24` case* |
| **D4** | **`Memory<Rgb24>`** |
|  *(T)*  | *Convert the `Rgb24` buffer to `TPixel` buffer using `PixelOperations<T>`* |
| **D5** | **The result image as an `TPixel` buffer** |

The magic is mostly in the D3->D4 transition, because of the fact that we can now do the pixel packing with [shuffle](https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference-intrinsics-for-shuffle-operations-1) and [permute](https://software.intel.com/en-us/cpp-compiler-developer-guide-and-reference-intrinsics-for-permute-operations) intrinsics when those are available. The other fun thing is that if we decode to `Image<Rgb24>` (case b) we can omit an unnecessary step.

# API proposal for packing
The best thing is that we can handle this big task incrementally:
- [x] First, extend `PixelOperations<T>` by new packing operations
- [ ] Then, adapt the changes in `JpegImagePostProcessor` as described in the *Optimized pipeline* paragraph 

The packing API is pretty straightforward:
```csharp
public class PixelOperations<TPixel>
{
    // ...
    
    public void PackFromRgbPlanes(
           Configuration configuration,
	   ReadOnlySpan<byte> redChannel, 
	   ReadOnlySpan<byte> greenChannel, 
	   ReadOnlySpan<byte> blueChannel,
	   Span<TPixel> destination);
}
```
We can define a default implementations in the base `PixelOperations<TPixel>` class, and specialize it for `Rgba32` and `Rgb24`. Optional hardcore task is to T4 a SIMD implementation it for all the RGB(A)-like formats.

#### Note
It is possible to optimize the conversion even further by doing D1->D3 in a single step, but I consider it a very hard task both implementation and architecture-wise, and prefer incremental evolution instead.

### LINKED ISSUE #1410: Non-generic Image.Load should decode Jpeg into Image<Rgb24>
Prerequsite: #1354

- Top gain: reduced memory footprint
- There will be a noticeable LoadResizeSave speed regression on 2.1 and Framework (no SIMD for shuffles), but I hope the ROTR / ROTL path will keep it in an acceptable range.
- On 3.1 and .NET 5 the LoadResizeSave  speed regression should be negligible thanks to the SIMD path in #1409
- #1396 combined with omitting [premultipication](https://github.com/SixLabors/ImageSharp/blob/adf56a4d77dc88252709fd7d080471ce2e2d0a3c/src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor%7BTPixel%7D.cs#L173-L174) for `Rgb24` will cancel out these regressions, bringing noticeable speedup on 3.1 and .NET 5. We may want to consider milestoning that issue to 1.1.0

### PR DESCRIPTION
**Pull request by antonfirsov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Finish the plan defined in #1410:
- Remove packing from JpegColorConverters and utilize #1462 `PixelOperations.PackFromRgbPlanes` instead
- Return `Image<Rgb24>` from non-generic Decode
- `ResizeProcessor<T>`:  omit alpha premultiplication if the pixel type has no alpha channel

Fixes #1410, fixes #1121.

### Performance

Did usual run of `LoadResizeSaveStressBenchmarks` on 10 core desktop. The overall effect on speed is within noise range, but there might be some 1%-ish improvement. I assume the reason is that #1462's packing actually doesn't make big difference to the packing code introduced in #1411.

But memory usage dropped significantly, which is the main goal here.

#### Before
```
|        Method | maxDegreeOfParallelism |       Mean |       Error |   StdDev | Ratio | RatioSD |     Gen 0 |     Gen 1 |     Gen 2 |    Allocated |
|-------------- |----------------------- |-----------:|------------:|---------:|------:|--------:|----------:|----------:|----------:|-------------:|
| SystemDrawing |                      1 | 8,711.9 ms |   862.64 ms | 47.28 ms |  1.00 |    0.00 |         - |         - |         - |        25 KB |
|    ImageSharp |                      1 | 5,218.4 ms |   135.62 ms |  7.43 ms |  0.60 |    0.00 | 3000.0000 | 3000.0000 | 3000.0000 | 1,226,257 KB |
|               |                        |            |             |          |       |         |           |           |           |              |
| SystemDrawing |                      5 | 3,128.0 ms | 1,188.61 ms | 65.15 ms |  1.00 |    0.00 |         - |         - |         - |        26 KB |
|    ImageSharp |                      5 | 1,516.9 ms |   782.02 ms | 42.86 ms |  0.49 |    0.02 | 2000.0000 | 2000.0000 | 2000.0000 | 1,226,402 KB |
|               |                        |            |             |          |       |         |           |           |           |              |
| SystemDrawing |                     10 | 2,828.7 ms |   786.61 ms | 43.12 ms |  1.00 |    0.00 |         - |         - |         - |        29 KB |
|    ImageSharp |                     10 |   823.4 ms |    80.49 ms |  4.41 ms |  0.29 |    0.01 | 1000.0000 | 1000.0000 | 1000.0000 | 1,229,766 KB |
|               |                        |            |             |          |       |         |           |           |           |              |
| SystemDrawing |                     20 | 2,793.0 ms |   735.65 ms | 40.32 ms |  1.00 |    0.00 |         - |         - |         - |        30 KB |
|    ImageSharp |                     20 |   686.0 ms |   570.78 ms | 31.29 ms |  0.25 |    0.01 | 1000.0000 | 1000.0000 | 1000.0000 | 1,237,201 KB |
```

#### After
```
|        Method | maxDegreeOfParallelism |       Mean |      Error |   StdDev | Ratio | RatioSD |     Gen 0 |     Gen 1 |     Gen 2 |  Allocated |
|-------------- |----------------------- |-----------:|-----------:|---------:|------:|--------:|----------:|----------:|----------:|-----------:|
| SystemDrawing |                      1 | 8,757.5 ms | 1,109.5 ms | 60.81 ms |  1.00 |    0.00 |         - |         - |         - |      25 KB |
|    ImageSharp |                      1 | 4,868.9 ms |   258.8 ms | 14.18 ms |  0.56 |    0.00 | 2000.0000 | 2000.0000 | 2000.0000 | 776,094 KB |
|               |                        |            |            |          |       |         |           |           |           |            |
| SystemDrawing |                      5 | 3,222.5 ms |   913.8 ms | 50.09 ms |  1.00 |    0.00 |         - |         - |         - |      27 KB |
|    ImageSharp |                      5 | 1,397.8 ms |   624.2 ms | 34.21 ms |  0.43 |    0.02 |         - |         - |         - | 776,093 KB |
|               |                        |            |            |          |       |         |           |           |           |            |
| SystemDrawing |                     10 | 2,849.4 ms | 1,590.1 ms | 87.16 ms |  1.00 |    0.00 |         - |         - |         - |      29 KB |
|    ImageSharp |                     10 |   852.6 ms |   576.0 ms | 31.57 ms |  0.30 |    0.02 | 1000.0000 | 1000.0000 | 1000.0000 | 843,968 KB |
|               |                        |            |            |          |       |         |           |           |           |            |
| SystemDrawing |                     20 | 2,764.5 ms | 1,152.1 ms | 63.15 ms |  1.00 |    0.00 |         - |         - |         - |      30 KB |
|    ImageSharp |                     20 |   622.7 ms |   475.5 ms | 26.07 ms |  0.23 |    0.01 | 1000.0000 | 1000.0000 | 1000.0000 | 949,029 KB |
```

/cc @br3aker @JimBobSquarePants @saucecontrol

### CODE REVIEW

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs [hunk 1]
```diff
@@ -40,23 +43,20 @@ public SpectralConverter(Configuration configuration, CancellationToken cancella
 
         private bool Converted => this.pixelRowCounter >= this.pixelBuffer.Height;
 
-        public Buffer2D<TPixel> PixelBuffer
+        public Buffer2D<TPixel> GetPixelBuffer()
```
Comment (antonfirsov) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs:46]: There is heavy lazy initialization, with side effects like `CancellationToken` firing. It's better to expose such stuff from a method than a property.

Comment (br3aker) [reply src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs:46]: I didn't like this property approach with a lot of lazy stuff behind from the start but couldn't come up with anything better. There's a lot of confusing bits of code here and there from my pr, I will work on decoder performance/refactoring next as I'm done with the encoder for now.

**Comment by JimBobSquarePants** [comment]
A lot of reading here. Will try to review tomorrow night

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgbVector8.cs [hunk 2]
```diff
@@ -18,50 +18,32 @@ public FromRgbVector8(int precision)
...
-                ref Vector<float> ggRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref gg);
-                ref Vector<float> bbRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref bb);
+                    ref Unsafe.As<float, Vector<float>>(ref MemoryMarshal.GetReference(values.Component2));
 
                 var scale = new Vector<float>(1 / this.MaximumValue);
 
                 // Walking 8 elements at one step:
-                int n = result.Length / 8;
+                int n = values.Component0.Length / 8;
                 for (int i = 0; i < n; i++)
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgbVector8.cs:34]:
```suggestion
                for (nint i = 0; i < n; i++)
```

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgbVector8.cs [hunk 3]
```diff
@@ -18,50 +18,32 @@ public FromRgbVector8(int precision)
...
-                ref Vector<float> rrRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref rr);
-                ref Vector<float> ggRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref gg);
-                ref Vector<float> bbRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref bb);
+                    ref Unsafe.As<float, Vector<float>>(ref MemoryMarshal.GetReference(values.Component2));
 
                 var scale = new Vector<float>(1 / this.MaximumValue);
 
                 // Walking 8 elements at one step:
-                int n = result.Length / 8;
+                int n = values.Component0.Length / 8;
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgbVector8.cs:33]:
```suggestion
                int n = (int)((uint)values.Component0.Length / 8);
```

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrAvx2.cs [hunk 4]
```diff
@@ -50,19 +47,19 @@ protected override void ConvertCoreVectorized(in ComponentValues values, Span<Ve
                 Vector256<int> vcontrol = Unsafe.As<byte, Vector256<int>>(ref control);
 
                 // Walking 8 elements at one step:
-                int n = result.Length / 8;
+                int n = values.Component0.Length / 8;
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrAvx2.cs:50]:
```suggestion
                int n = (int)((uint)(values.Component0.Length / 8);
```

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrAvx2.cs [hunk 5]
```diff
@@ -50,19 +47,19 @@ protected override void ConvertCoreVectorized(in ComponentValues values, Span<Ve
...
                 for (int i = 0; i < n; i++)
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrAvx2.cs:51]:
```suggestion
                for (nint i = 0; i < n; i++)
```

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector4.cs [hunk 6]
```diff
@@ -20,73 +20,69 @@ public FromYCbCrVector4(int precision)
...
 
-                ref Vector4Octet resultBase =
-                    ref Unsafe.As<Vector4, Vector4Octet>(ref MemoryMarshal.GetReference(result));
-
                 var chromaOffset = new Vector4(-this.HalfValue);
                 var maxValue = this.MaximumValue;
 
                 // Walking 8 elements at one step:
-                int n = result.Length / 8;
+                int n = values.Component0.Length / 8;
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector4.cs:38]:
```suggestion
                int n = (int)((uint)values.Component0.Length / 8);
```

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector4.cs [hunk 7]
```diff
@@ -20,73 +20,69 @@ public FromYCbCrVector4(int precision)
...
 
                 for (int i = 0; i < n; i++)
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector4.cs:40]:
```suggestion
                for (nint i = 0; i < n; i++)
```

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector8.cs [hunk 8]
```diff
@@ -19,41 +19,32 @@ public FromYCbCrVector8(int precision)
...
-
-                Vector4Pair rr = default;
-                Vector4Pair gg = default;
-                Vector4Pair bb = default;
-
-                ref Vector<float> rrRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref rr);
-                ref Vector<float> ggRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref gg);
-                ref Vector<float> bbRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref bb);
-
+                int n = values.Component0.Length / 8;
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector8.cs:34]:
```suggestion
                int n = (int)((uint)values.Component0.Length / 8);
```
or maybe create a helper for this? The casts aren't very intuitive, but codegen is quite a difference.

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector8.cs [hunk 9]
```diff
@@ -19,41 +19,32 @@ public FromYCbCrVector8(int precision)
...
                 var scale = new Vector<float>(1 / this.MaximumValue);
 
                 for (int i = 0; i < n; i++)
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector8.cs:37]:
```suggestion
                for (nint i = 0; i < n; i++)
```

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYccKAvx2.cs [hunk 10]
```diff
@@ -22,52 +22,42 @@ public FromYccKAvx2(int precision)
...
 
-                // Used for packing.
-                var va = Vector256.Create(1F);
-                ref byte control = ref MemoryMarshal.GetReference(HwIntrinsics.PermuteMaskEvenOdd8x32);
-                Vector256<int> vcontrol = Unsafe.As<byte, Vector256<int>>(ref control);
-
                 // Walking 8 elements at one step:
-                int n = result.Length / 8;
+                int n = values.Component0.Length / 8;
                 for (int i = 0; i < n; i++)
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYccKAvx2.cs:48]:
```suggestion
                int n = (int)((uint)values.Component0.Length / 8);
                for (nint i = 0; i < n; i++)
```

Now I'll stop commenting on these -- otherwise it's too much noise generated by me 😉

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYccKVector8.cs [hunk 11]
```diff
@@ -18,34 +18,23 @@ public FromYccKVector8(int precision)
...
-                Vector4Pair bb = default;
-
-                ref Vector<float> rrRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref rr);
-                ref Vector<float> ggRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref gg);
-                ref Vector<float> bbRefAsVector = ref Unsafe.As<Vector4Pair, Vector<float>>(ref bb);
+                int n = values.Component0.Length / 8;
 
-                var scale = new Vector<float>(1 / this.MaximumValue);
+                var scale = new Vector<float>(1 / (this.MaximumValue * this.MaximumValue));
                 var max = new Vector<float>(this.MaximumValue);
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYccKVector8.cs:38]:
```suggestion
                var max = new Vector<float>(this.MaximumValue);
                var scale = new Vector<float>(1f) / (max * max);
```
is [less ceremony](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9JqwByHAVGXqamgMxNSDIQwDeNBg6bmAZpIjYMDALLYE/fQBq2JIcMLYMAOYwGGoMuNGxAL72jikOYoYKHmEBMGAY0AA8ru4YAHwMAPq4YMEwGtSODBm8WRg5eQVQxW4eFZX4vg1NaU5MKAwAggAUAJSjdo1NjtW10gwAvAxcMADuDLn5RSV90+QMAPQM0xgAFry4LD5++IHBoQwAVAx3D0++/nwQRCMFms2GywcA18m22ewOnWOvXKN3uj2egOBoXBo2SSwco2I5mIEwAQnMFqMmlkoAxBghYTt9ocuj1SmVUX8Ma8ge9QRDIdCGVt6QLllTHDS4mswlsmQijt0TijyM4cfjlqs6rCatqrtN6V86b51U08YkgA).

File: src/ImageSharp/Memory/DiscontiguousBuffers/MemoryGroupExtensions.cs [hunk 12]
```diff
@@ -61,6 +61,35 @@ internal static Memory<T> GetBoundedSlice<T>(this IMemoryGroup<T> group, long st
...
+        internal static Memory<T> GetRemainingSliceOfBuffer<T>(this IMemoryGroup<T> group, long start)
+            where T : struct
+        {
+            Guard.NotNull(group, nameof(group));
+            Guard.IsTrue(group.IsValid, nameof(group), "Group must be valid!");
+            Guard.MustBeLessThan(start, group.TotalLength, nameof(start));
+
+            int bufferIdx = (int)(start / group.BufferLength);
+
+            if (bufferIdx < 0)
```
Comment (gfoidl) [inline src/ImageSharp/Memory/DiscontiguousBuffers/MemoryGroupExtensions.cs:76]: Can combine with the check below by using
```c#
if ((uint)bufferIdx >= group.Count)
{
   ...
}
```
A negative value for `bufferIdx` is after the `uint` cast in the range > int.MaxValue, so definitely >= group.Count too.

**Review by gfoidl — COMMENTED** [review]
Just a quick look over the code, not detailed review.

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgbVector8.cs (hunk 3 above)
Comment (antonfirsov) [reply src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgbVector8.cs]: I think this trick is only worth it when we are inside a tight loop or, or in a method that is expected to be called from a loop. Otherwise I prefer readability.

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector4.cs (hunk 6 above)
Comment (antonfirsov) [reply src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector4.cs]: I'm not sure it's worth it, see https://github.com/SixLabors/ImageSharp/pull/1773#discussion_r720905777

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector8.cs (hunk 8 above)
Comment (antonfirsov) [reply src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYCbCrVector8.cs]: I'm not sure it's worth it, see https://github.com/SixLabors/ImageSharp/pull/1773#discussion_r720905777

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgbVector8.cs (hunk 3 above)
Comment (antonfirsov) [reply src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgbVector8.cs]: Or is it possible to achieve the same in a simpler way `nint`? I changed my code everywhere to `nint n = values.Component0.Length / 8;` because `n` is only used for the `i < n` comparison.

Comment (gfoidl) [reply src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgbVector8.cs]: We should go with readability, as you did now with `nint`. Codegen isn't ideal, but this pattern `{array, span}.Length / ConstantOfPowerOfTwo` is so common, that the JIT should be able to optimize this, so we don't need any hacks.
I'll have a look if there's a JIT-issue, otherwise create one.

File: src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromGrayScaleBasic.cs [hunk 13]
```diff
@@ -17,25 +17,35 @@ public FromGrayscaleBasic(int precision)
...
+                if (!values.IsEmpty)
+                {
+                    float scaleValue = 1f / maxValue;
+                    values[0] *= scaleValue;
+
+                    if (values.Length > 1)
+                    {
+                        values[1] *= scaleValue;
+
+                        if (values.Length > 2)
```
Comment (gfoidl) [inline src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromGrayScaleBasic.cs:44]:
```suggestion
                    if ((uint)values.Length > 1)
                    {
                        values[1] *= scaleValue;

                        if ((uint)values.Length > 2)
```
Elides further bound checks.
(Sorry that I didn't comment on that yesterday)

**Review by JimBobSquarePants — APPROVED** [review]
I can't believe how much easier the code is to read now! I did a few readthroughs just to make sure I wasn't missing something 😄 

Just @gfoidl last suggestion and it's good to go. 👍

File: src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs [hunk 14]
```diff
@@ -187,6 +188,8 @@ private static PixelConversionModifiers GetModifiers(bool compand, bool premulti
             bool compand,
             bool premultiplyAlpha)
         {
+            bool pixelHasNoAlpha = PixelOperations<TPixel>.Instance.GetPixelTypeInfo()?.AlphaRepresentation == PixelAlphaRepresentation.None;
+            premultiplyAlpha &= !pixelHasNoAlpha;
```
Comment (antonfirsov) [inline src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs:192]: @JimBobSquarePants I couldn't figure out how should this *really* work with our existing pixel types, so went with the safest option here (only omit premultiplication when we are 100% sure that the alpha channel is missing).

However, if I understand it correctly normally we should only premultiply in case of `PixelAlphaRepresentation.Associated`. What confuses me is that `Rgba32` and friends are configured to `Unassociated`:

https://github.com/SixLabors/ImageSharp/blob/97dde7fb2f0ac97b5b1f9e6b0555a53d2e270c46/src/ImageSharp/PixelFormats/PixelImplementations/PixelOperations/Rgba32.PixelOperations.cs#L22-L23

Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs:192]: Ah no. Associated alpha means premultiplied. The only occasion we should premultiply is `PixelAlphaRepresentation.Unassociated`
https://en.wikipedia.org/wiki/Alpha_compositing#Straight_versus_premultiplied

Comment (antonfirsov) [reply src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs:192]: Thanks, I see now!

Would be the following code better here then?
```suggestion
            PixelAlphaRepresentation? alphaRepresentation = PixelOperations<TPixel>.Instance.GetPixelTypeInfo()?.PixelAlphaRepresentation;

            // Premultiply only if alpha representation is unknown or Unassociated:
            bool needsPremultiplication = alphaRepresentation == null || alphaRepresentation.Value == PixelAlphaRepresentation.Unassociated;
            premultiplyAlpha &= needsPremultiplication;
```

Comment (JimBobSquarePants) [reply src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs:192]: Yep. That looks good to me. 👍

File: src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs [hunk 15]
```diff
@@ -187,6 +188,11 @@ private static PixelConversionModifiers GetModifiers(bool compand, bool premulti
             bool compand,
             bool premultiplyAlpha)
         {
+            PixelAlphaRepresentation? alphaRepresentation = PixelOperations<TPixel>.Instance.GetPixelTypeInfo()?.PixelAlphaRepresentation;
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs:191]:
```suggestion
            PixelAlphaRepresentation? alphaRepresentation = PixelOperations<TPixel>.Instance.GetPixelTypeInfo()?.AlphaRepresentation;
```
