### PR TITLE
#797 throw ImageFormatException when no StartOfFrame marker is found

### LINKED ISSUE #797: Image.Load throws NullReferenceException
**Image.Load** throws a **NullReferenceException** when loading the image from the [attached archive]. You can run the following code to reproduce it (the **path** variable should contain the path to the extracted file):

```csharp
Image.Load(path);
```

Found via [SharpFuzz].

[attached archive]: https://github.com/SixLabors/ImageSharp/files/2707118/NullReferenceException.zip
[SharpFuzz]: https://github.com/Metalnem/sharpfuzz

### PR DESCRIPTION
**Pull request by jongleur1983**
### Prerequisites
- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
Fixes #797:

For jpg images where we can't find a valid SOF (start of frame) marker we now throw an ImageFormatException reporting that fact instead of a NullReferenceException.

Added the failing image from the issue for a test case.

### CODE REVIEW

File: src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs [hunk 1]
```diff
@@ -292,6 +292,11 @@ public void ParseStream(Stream stream, bool metadataOnly = false)
                         case JpegConstants.Markers.SOS:
                             if (!metadataOnly)
                             {
+                                if (this.Frame is null)
+                                {
+                                    throw new ImageFormatException("no readable SOF marker found.");
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs]: Can you change this to say "No readable SOFn (Start Of Frame) marker found" and move the check to `ProcessStartOfScanMarker()`

Comment (jongleur1983) [reply src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs]: sure, done.
