### PR TITLE
V3: Gracefully handle LZW overflows

### LINKED ISSUE #2859: AccessViolationException when decoding gif
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.6

### Other ImageSharp packages and versions

N/A

### Environment (Operating system, version and so on)

Windows 11

### .NET Framework version

.NET 8

### Description

Loading the attached gif causes an AccessViolationException and brings down the process.

 ```
at SixLabors.ImageSharp.Formats.Gif.LzwDecoder.DecodePixelRow(System.Span`1<Byte>)
 at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrameColors[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.IO.BufferedReadStream, SixLabors.ImageSharp.Image`1<SixLabors.ImageSharp.PixelFormats.Rgba32> ByRef, SixLabors.ImageSharp.ImageFrame`1<SixLabors.ImageSharp.PixelFormats.Rgba32> ByRef, System.ReadOnlySpan`1<SixLabors.ImageSharp.PixelFormats.Rgb24>, SixLabors.ImageSharp.Formats.Gif.GifImageDescriptor ByRef)
 at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.ReadFrame[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.IO.BufferedReadStream, SixLabors.ImageSharp.Image`1<SixLabors.ImageSharp.PixelFormats.Rgba32> ByRef, SixLabors.ImageSharp.ImageFrame`1<SixLabors.ImageSharp.PixelFormats.Rgba32> ByRef)
 at SixLabors.ImageSharp.Formats.Gif.GifDecoderCore.Decode[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.IO.BufferedReadStream, System.Threading.CancellationToken)
 at SixLabors.ImageSharp.Formats.ImageDecoderCore.Decode[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.Configuration, System.IO.Stream, System.Threading.CancellationToken)
 at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.Formats.DecoderOptions, System.IO.Stream, System.Threading.CancellationToken)
 at SixLabors.ImageSharp.Formats.Gif.GifDecoder.Decode(SixLabors.ImageSharp.Formats.DecoderOptions, System.IO.Stream, System.Threading.CancellationToken)
 at SixLabors.ImageSharp.Formats.ImageDecoder+<>c__DisplayClass1_0.<Decode>b__0(System.IO.Stream)
 at SixLabors.ImageSharp.Formats.ImageDecoder.<WithSeekableStream>g__PerformActionAndResetPosition|11_0[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.IO.Stream, Int64, <>c__DisplayClass11_0`1<System.__Canon> ByRef)
 at SixLabors.ImageSharp.Formats.ImageDecoder.WithSeekableStream[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](SixLabors.ImageSharp.Formats.DecoderOptions, System.IO.Stream, System.Func`2<System.IO.Stream,System.__Canon>)
 at SixLabors.ImageSharp.Formats.ImageDecoder.Decode(SixLabors.ImageSharp.Formats.DecoderOptions, System.IO.Stream)
 at SixLabors.ImageSharp.Image.Decode(SixLabors.ImageSharp.Formats.DecoderOptions, System.IO.Stream)
 at SixLabors.ImageSharp.Image+<>c__DisplayClass80_0.<Load>b__0(System.IO.Stream)
 at SixLabors.ImageSharp.Image.WithSeekableStream[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](SixLabors.ImageSharp.Formats.DecoderOptions, System.IO.Stream, System.Func`2<System.IO.Stream,System.__Canon>)
 at SixLabors.ImageSharp.Image.Load(SixLabors.ImageSharp.Formats.DecoderOptions, System.IO.Stream)
 at SixLabors.ImageSharp.Image.Load(System.IO.Stream)
```

### Steps to Reproduce

```csharp
using var image = Image.Load("corrupt.gif");
```

### Images

corrupt

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description

The issue is caused by using the full capacity of the pixel stack for intermediate pushes without reserving a slot for the final push, which leads to an overflow. By capping out the max index we can skip corrupt blocks. 

Fixes #2859

### CODE REVIEW

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs [hunk 1]
```diff
@@ -204,7 +205,7 @@ public void DecodePixelRow(Span<byte> indices)
                     this.code = this.oldCode;
                 }
 
-                while (this.code > this.clearCode)
+                while (this.code > this.clearCode && this.top < maxTop)
```
[the remark this answers is not in the document]
Comment (JimBobSquarePants) [reply src/ImageSharp/Formats/Gif/LzwDecoder.cs:208]: Only if we can get the same performance out. We're hitting two separate spans inside a loop which is will definitely incur bounds checks costs.

[the remark this answers is not in the document]
Comment (JimBobSquarePants) [reply src/ImageSharp/Formats/Gif/LzwDecoder.cs]: @antonfirsov I've updated the `LzwDecoder` with the best I could do performance-wise using safe code.

I'm OK with the performance hit given the much-improved security.  Given that System.Drawing doesn't actually fully decode the image I'm still happy with the the performance of the decoder.

**Target Branch**

```
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.26100
11th Gen Intel Core i7-11370H 3.30GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=9.0.200-preview.0.25057.12
  [Host]     : .NET 7.0.20 (7.0.2024.26716), X64 RyuJIT
  Job-AUXYJW : .NET 6.0.36 (6.0.3624.51421), X64 RyuJIT

Runtime=.NET 6.0  Arguments=/p:DebugType=portable  IterationCount=3
LaunchCount=1  WarmupCount=3
```

|               Method |     TestImage |     Mean |     Error |  StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------- |-------------- |---------:|----------:|--------:|------:|--------:|-------:|------:|------:|----------:|
| 'System.Drawing Gif' | Gif/rings.gif | 294.7 us | 100.98 us | 5.53 us |  1.00 |    0.00 |      - |     - |     - |     168 B |
|     'ImageSharp Gif' | Gif/rings.gif | 410.6 us |  87.95 us | 4.82 us |  1.39 |    0.03 | 0.9766 |     - |     - |   7,557 B |


**This PR**

|               Method |     TestImage |     Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------- |-------------- |---------:|---------:|---------:|------:|--------:|-------:|------:|------:|----------:|
| 'System.Drawing Gif' | Gif/rings.gif | 299.0 us | 189.8 us | 10.41 us |  1.00 |    0.00 |      - |     - |     - |     168 B |
|     'ImageSharp Gif' | Gif/rings.gif | 486.9 us | 153.3 us |  8.40 us |  1.63 |    0.06 | 0.9766 |     - |     - |   7,715 B |

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs [hunk 2]
```diff
@@ -132,112 +132,140 @@ public void DecodePixelRow(Span<byte> indices)
...
 
             // Pop a pixel off the pixel stack.
-            this.top--;
+            top--;
 
-            // Clear missing pixels
-            xyz++;
-            Unsafe.Add(ref pixelsRowRef, (uint)x++) = (byte)Unsafe.Add(ref pixelStackRef, (uint)this.top);
+            // Clear missing pixels.
+            indices[xyz++] = (byte)pixelStack[top];
```
Comment (antonfirsov) [inline src/ImageSharp/Formats/Gif/LzwDecoder.cs:254]: Since xyz seems to run till `indices.Length` this can be a straightforward for-loop.

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs [hunk 3]
```diff
@@ -132,112 +132,140 @@ public void DecodePixelRow(Span<byte> indices)
...
                     }
                 }
 
-                this.oldCode = inCode;
+                oldCode = inCode;
             }
 
             // Pop a pixel off the pixel stack.
-            this.top--;
+            top--;
```
Comment (antonfirsov) [inline src/ImageSharp/Formats/Gif/LzwDecoder.cs:251]: Is there a some logical guarantee that `top` doesn't run below zero?

**Review by antonfirsov — APPROVED** [review]
LGTM. The ~15-20%  regression seems somewhat worse than what I expected, but I think we can improve on that by micro-optimizations.

Mentioning a few suggestions I found, but they might be not the most efficient ideas, I'm  OK adding them in another PR if you prefer so.

The ideal approach would be to profile the code anyways. If that detects some indexing bottlenecks which can't be eliminated by other means, I wouldn't be against limited *surgical* applications of Unsafe, but those should come with a very mindful, well-documented analysis of the code arguing the usage is correct.

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs [hunk 4]
```diff
@@ -93,10 +92,11 @@ public LzwDecoder(MemoryAllocator memoryAllocator, BufferedReadStream stream, in
...
         this.availableCode = this.clearCode + 2;
 
-        ref int suffixRef = ref MemoryMarshal.GetReference(this.suffix.GetSpan());
-        for (this.code = 0; this.code < this.clearCode; this.code++)
+        Span<int> suffix = this.suffixOwner.GetSpan();
+        int max = Math.Min(this.clearCode, suffix.Length);
+        for (this.code = 0; this.code < max; this.code++)
         {
-            Unsafe.Add(ref suffixRef, (uint)this.code) = (byte)this.code;
+            suffix[this.code] = (byte)this.code;
```
Comment (antonfirsov) [inline src/ImageSharp/Formats/Gif/LzwDecoder.cs:99]: This could run on a slice of `suffix`.

Comment (antonfirsov) [reply src/ImageSharp/Formats/Gif/LzwDecoder.cs:99]: Or if there is an upper limit to `Math.Min(this.clearCode, suffix.Length)`, it can be copied out from a statically initialized buffer.

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs (hunk 2 above)
Comment (JimBobSquarePants) [reply src/ImageSharp/Formats/Gif/LzwDecoder.cs:254]: We don't always increment on each iteration so that's not possible. We can certainly inline the incremental though.

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs (hunk 3 above)
Comment (JimBobSquarePants) [reply src/ImageSharp/Formats/Gif/LzwDecoder.cs:251]: As soon as we hit zero we enter the condition above. In there I believe there's at least one condition that increments `top` by one. The worst thing that could ever happen if `top` fals below zero is that we skip to the end of the pixel indices.

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs (hunk 4 above)
Comment (JimBobSquarePants) [reply src/ImageSharp/Formats/Gif/LzwDecoder.cs:99]: Clear code maxes out at 256. We can certainly slice here.

File: src/ImageSharp/Formats/Gif/LzwDecoder.cs [hunk 5]
```diff
@@ -132,112 +132,140 @@ public void DecodePixelRow(Span<byte> indices)
...
                 // https://bugzilla.mozilla.org/show_bug.cgi?id=55918
-                if (this.availableCode < MaxStackSize)
+                if (availableCode < MaxStackSize)
                 {
-                    Unsafe.Add(ref prefixRef, (uint)this.availableCode) = this.oldCode;
-                    Unsafe.Add(ref suffixRef, (uint)this.availableCode) = this.first;
-                    this.availableCode++;
-                    if (this.availableCode == this.codeMask + 1 && this.availableCode < MaxStackSize)
+                    prefix[availableCode] = oldCode;
+                    suffix[availableCode] = first;
```
[the remark this answers is not in the document]
Comment (JimBobSquarePants) [reply src/ImageSharp/Formats/Gif/LzwDecoder.cs:238]: I think I understand you and had a look. It seems like this would make the code a little more difficult to follow so have left it.

**Comment by JimBobSquarePants** [comment]
@antonfirsov Managed to squeeze a little more performance out of this. Still haven't done any profiling though. Will merge once built.

BenchmarkDotNet=v0.13.0, OS=Windows 10.0.26100
11th Gen Intel Core i7-11370H 3.30GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=9.0.200-preview.0.25057.12
  [Host]     : .NET 7.0.20 (7.0.2024.26716), X64 RyuJIT
  Job-JWXLPI : .NET 6.0.36 (6.0.3624.51421), X64 RyuJIT

Runtime=.NET 6.0  Arguments=/p:DebugType=portable  IterationCount=3
LaunchCount=1  WarmupCount=3
```
|               Method |     TestImage |     Mean |     Error |  StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------- |-------------- |---------:|----------:|--------:|------:|--------:|-------:|------:|------:|----------:|
| 'System.Drawing Gif' | Gif/rings.gif | 281.1 us | 156.76 us | 8.59 us |  1.00 |    0.00 |      - |     - |     - |     173 B |
|     'ImageSharp Gif' | Gif/rings.gif | 434.7 us |  66.17 us | 3.63 us |  1.55 |    0.06 | 0.9766 |     - |     - |   7,401 B |
