### PR TITLE
Reduce the number of memory allocations in lossless WebP encoder

### LINKED ISSUE #2934: Lossless WebP encoder allocates A LOT
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp version

3.1.8

### Other ImageSharp packages and versions

-

### Environment (Operating system, version and so on)

Windows 11 with latest updates

### .NET Framework version

.NET 9

### Description

Lossless WebP encoder allocates both a lot of small object and also a few big chunks, which are NOT reused.
It is about 500 K objects and 200-300 MB total memory to encode single UWQHD (3440x1440) image.
It leads to very high pressure on GC. Especially, if there are many images to process.

Me encoding settings are probably the lowest for lossless saving:
```csharp
WebpEncoder {
    FileFormat = WebpFileFormatType.Lossless,
    Quality = 0,
    TransparentColorMode = WebpTransparentColorMode.Preserve,
}
```

I found the following hot paths (for one image):
Image
Image

`PixOrCopy.CreateLiteral` produces TONS of small objects.
`Vp8LEncoder`'s constructor may not look that scary, but let's sequentially encode 10 images:
Image
Image

As you can see, those big chunks are not reused in the future.
I tried to provide a custom memory allocator. It didn't help.
I suppose the allocator is totally ignored there.

Fixing these two moments should greatly accelerate the WebP encoder:
1. `PixOrCopy.CreateLiteral` problem is probably the hardest one as it requires changing of data structures.
2. Changing `Vp8LEncoder` should be much easier.

### Steps to Reproduce

Just encode an image with performance profiles and object allocation tracking.

### Images

_No response_

### PR DESCRIPTION
**Pull request by SladeThe**
This PR closes #2934

The results of benchmark `#55 EncodeWebp`:

#### Before
| Method                     | Mean      | Error     | StdDev   | Gen0      | Gen1      | Gen2      | Allocated   |
|--------------------------- |----------:|----------:|---------:|----------:|----------:|----------:|------------:|
| 'ImageSharp Webp Lossless' | 105.31 ms | 24.582 ms | 1.347 ms | 2000.0000 | 1800.0000 | 1400.0000 | 20490.55 KB |

#### After
| Method                     | Mean      | Error     | StdDev   | Gen0      | Gen1      | Gen2      | Allocated   |
|--------------------------- |----------:|----------:|---------:|----------:|----------:|----------:|------------:|
| 'ImageSharp Webp Lossless' | 100.61 ms | 15.196 ms | 0.833 ms | 2000.0000 | 2000.0000 | 2000.0000 |  3904.68 KB |

#### Pin the refs (without the capacity guard)
| Method                     | Mean      | Error     | StdDev   | Gen0      | Gen1      | Gen2      | Allocated   |
|--------------------------- |----------:|----------:|---------:|----------:|----------:|----------:|------------:|
| 'ImageSharp Webp Lossless' |  97.43 ms |  9.375 ms | 0.514 ms |   2000.0000 | 2000.0000 | 2000.0000 |  3904.98 KB |

### CODE REVIEW

File: src/ImageSharp/Formats/Webp/Lossless/HistogramEncoder.cs [hunk 1]
```diff
@@ -109,10 +109,9 @@ private static void HistogramBuild(
...
         int x = 0, y = 0;
         int histoXSize = LosslessUtils.SubSampleSize(xSize, histoBits);
-        using List<PixOrCopy>.Enumerator backwardRefsEnumerator = backwardRefs.Refs.GetEnumerator();
-        while (backwardRefsEnumerator.MoveNext())
+
+        foreach (PixOrCopy v in backwardRefs)
         {
-            PixOrCopy v = backwardRefsEnumerator.Current;
             int ix = ((y >> histoBits) * histoXSize) + (x >> histoBits);
             histograms[ix].AddSinglePixOrCopy(v, false);
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Formats/Webp/Lossless/HistogramEncoder.cs]: This method could be updated to take the struct via `in` to avoid the copy.

File: src/ImageSharp/Formats/Webp/Lossless/Vp8LBackwardRefs.cs [hunk 2]
```diff
@@ -1,21 +1,28 @@
...
+    private readonly IMemoryOwner<PixOrCopy> refs;
+    private int count;
+
+    public Vp8LBackwardRefs(MemoryAllocator memoryAllocator, int pixels)
+    {
+        this.refs = memoryAllocator.Allocate<PixOrCopy>(pixels);
+        this.count = 0;
+    }
+
+    public void Add(PixOrCopy pixOrCopy) => this.refs.Memory.Span[this.count++] = pixOrCopy;
```
Comment (JimBobSquarePants) [inline src/ImageSharp/Formats/Webp/Lossless/Vp8LBackwardRefs.cs:20]: I imaging resolving the span here is a strong candidate for any slowdown using pooled memory.

**Review by JimBobSquarePants — COMMENTED** [review]
Just a quick read so far but looking good. I'll have to pull it down to review properly.

File: src/ImageSharp/Formats/Webp/Lossless/HistogramEncoder.cs (hunk 1 above)
Comment (SladeThe) [reply src/ImageSharp/Formats/Webp/Lossless/HistogramEncoder.cs]: I've made the change. But if there is any performance difference, it's hard to notice. The structure is not that big.

File: src/ImageSharp/Formats/Webp/Lossless/Vp8LBackwardRefs.cs (hunk 2 above)
Comment (antonfirsov) [reply src/ImageSharp/Formats/Webp/Lossless/Vp8LBackwardRefs.cs:20]: I'm getting the code right that `Vp8LBackwardRefs` is a temporary object? If yes, we could `Pin` the memory in the ctr, store the handle and the `PixOrCopy*` pointer and `Unpin` the handle in `Dispose`.

Comment (SladeThe) [reply src/ImageSharp/Formats/Webp/Lossless/Vp8LBackwardRefs.cs:20]: You are right. The resolving here is quite slow.
That's why I switched from index-based `refs` access to `foreach` in my [second commit](https://github.com/SixLabors/ImageSharp/pull/2940/commits/ff9d3a6223c72ca1c5931593e404ce0070db9d9c).

However, the whole change still makes the encoder almost 5% faster.
Also, the result is more stable and less affected by GC pauses (see the reduced Error value in my first post).
The `refs` are read-mostly, and I don't think that relatively slow `Add` is such a big problem.

Comment (SladeThe) [reply src/ImageSharp/Formats/Webp/Lossless/Vp8LBackwardRefs.cs:20]: I've pinned the `refs` and got even better results.
Added it to the top post.
Thank you for pointing it out.

Comment (antonfirsov) [reply src/ImageSharp/Formats/Webp/Lossless/Vp8LBackwardRefs.cs:20]: Wow, exposing `Span<PixOrCopy>.Enumerator` is neat, haven't noticed that!

> still makes the encoder almost 5% faster

In that case I agree that spending effort and increasing complexity to optimize `Add()` is not worth the trouble in this PR. We can profile and optimize the encoder later if we want.

Comment (SladeThe) [reply src/ImageSharp/Formats/Webp/Lossless/Vp8LBackwardRefs.cs:20]: I've just realised, the the pointer access became unsafe.

After storing the span capacity in a field and adding the guard to `Add`, the performance switched to about the same value as it was before the last commit.

Now I tend reverting the commit. At least, for code brevity.

**Review by antonfirsov — APPROVED** [review]
Looks good after skimming through all changes.

**Comment by JimBobSquarePants** [comment]
I'm thinking of backporting this to V3. @antonfirsov what do you think?

**Comment by antonfirsov** [comment]
The change looks simple and safe enough to backport.

**Comment by JimBobSquarePants** [comment]
Thanks for this @SladeThe it's very much appreciated!!
